services:
  # Backend de Autenticación
  gamc-auth-backend:
    build:
      context: ./backend-auth
      dockerfile: Dockerfile
    container_name: gamc_auth_backend
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 3000
      API_PREFIX: /api/v1
      DATABASE_URL: postgresql://gamc_user:gamc_password_2024@gamc_postgres:5432/gamc_system
      REDIS_URL: redis://:gamc_redis_password_2024@gamc_redis:6379/0
      JWT_SECRET: gamc_jwt_secret_super_secure_2024_key_never_share
      JWT_REFRESH_SECRET: gamc_jwt_refresh_secret_super_secure_2024_key
      JWT_EXPIRES_IN: 15m
      JWT_REFRESH_EXPIRES_IN: 7d
      CORS_ORIGIN: http://localhost:5173
      TZ: America/La_Paz
    ports:
      - "3000:3000"
    volumes:
      # Hot reload - montar código fuente
      - ./backend-auth/src:/app/src:ro
      - ./backend-auth/prisma:/app/prisma:ro
      - ./backend-auth/.env:/app/.env:ro
      # Excluir node_modules para mejor performance
      - /app/node_modules
    networks:
      - gamc_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Sin depends_on porque están en compose files separados

  # Frontend de Autenticación
  gamc-auth-frontend:
    build:
      context: ./frontend-auth
      dockerfile: Dockerfile
      target: development
    container_name: gamc_auth_frontend
    restart: unless-stopped
    environment:
      VITE_API_URL: http://localhost:3000/api/v1
      VITE_APP_NAME: GAMC Auth System
    ports:
      - "5173:5173"
    volumes:
      # Hot reload - montar código fuente
      - ./frontend-auth/src:/app/src:ro
      - ./frontend-auth/public:/app/public:ro
      - ./frontend-auth/index.html:/app/index.html:ro
      - ./frontend-auth/vite.config.ts:/app/vite.config.ts:ro
      - ./frontend-auth/tailwind.config.js:/app/tailwind.config.js:ro
      - ./frontend-auth/postcss.config.js:/app/postcss.config.js:ro
      # Excluir node_modules
      - /app/node_modules
    depends_on:
      - gamc-auth-backend
    networks:
      - gamc_network

networks:
  gamc_network:
    external: true