services:
  # MinIO Server - Almacenamiento de objetos S3-compatible
  minio:
    image: minio/minio:latest
    container_name: gamc_minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: gamc_admin
      MINIO_ROOT_PASSWORD: gamc_minio_password_2024
      MINIO_BROWSER_REDIRECT_URL: http://localhost:9001
      MINIO_SERVER_URL: http://localhost:9000
      TZ: America/La_Paz
    ports:
      - "9000:9000"  # API
      - "9001:9001"  # Console Web UI
    volumes:
      # Datos persistentes
      - minio_data:/data
      # Configuración
      - ./config:/root/.minio
      # Políticas personalizadas
      - ./policies:/policies:ro
    networks:
      - gamc_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 60s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # MinIO Client para administración automatizada
  minio-client:
    image: minio/mc:latest
    container_name: gamc_minio_client
    restart: "no"
    environment:
      TZ: America/La_Paz
    volumes:
      - ./scripts:/scripts:ro
      - ./config:/root/.mc
    networks:
      - gamc_network
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      echo 'Configurando MinIO Client...';
      mc alias set gamc-local http://minio:9000 gamc_admin gamc_minio_password_2024;
      echo 'Creando buckets necesarios...';
      mc mb gamc-local/gamc-attachments --ignore-existing;
      mc mb gamc-local/gamc-documents --ignore-existing;
      mc mb gamc-local/gamc-images --ignore-existing;
      mc mb gamc-local/gamc-backups --ignore-existing;
      mc mb gamc-local/gamc-temp --ignore-existing;
      mc mb gamc-local/gamc-reports --ignore-existing;
      echo 'Configurando políticas de acceso...';
      mc anonymous set download gamc-local/gamc-images;
      mc anonymous set download gamc-local/gamc-documents;
      echo 'Configuración completada.';
      if [ -f /scripts/setup-buckets.sh ]; then
        echo 'Ejecutando configuración adicional...';
        chmod +x /scripts/setup-buckets.sh;
        /scripts/setup-buckets.sh;
      fi;
      echo 'MinIO Client configurado exitosamente.';
      "
    profiles:
      - setup

  # MinIO Gateway para desarrollo (opcional)
  minio-gateway:
    image: nginx:alpine
    container_name: gamc_minio_gateway
    restart: unless-stopped
    ports:
      - "8090:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/html:/usr/share/nginx/html:ro
    networks:
      - gamc_network
    depends_on:
      minio:
        condition: service_healthy
    profiles:
      - gateway

volumes:
  minio_data:
    driver: local
    name: gamc_minio_data

networks:
  gamc_network:
    external: true
    name: gamc_network